name: electron-cash
version: master
summary: Bitcoin Cash thin client
description: |
  Lightweight Bitcoin Cash client

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  electron-cash:
    command: desktop-launch electron-cash
    plugs: [network, network-bind, x11, unity7]

parts:
  electron-cash:
    source: .
    plugin: python
    python-version: python2
    stage-packages: [python-qt5]
    build-packages: [pyqt5-dev-tools]
    install: pyrcc5 icons.qrc -o $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/electroncash_gui/qt/icons_rc.py
    after: [desktop-qt5]
